schema = 3

[mod]
  [mod."github.com/cpuguy83/go-md2man/v2"]
    version = "v2.0.2"
    hash = "sha256-OvWCtDsVrYzM84SMQwOXPLBxnWnMC1hDm+KiI6zm3uk="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/hashicorp/errwrap"]
    version = "v1.0.0"
    hash = "sha256-LGSLrefkABG1kH1i+GUWiD2/ggJxiZEJ+D2YNbhZjmo="
  [mod."github.com/hashicorp/go-multierror"]
    version = "v1.1.1"
    hash = "sha256-ANzPEUJIZIlToxR89Mn7Db73d9LGI51ssy7eNnUgmlA="
  [mod."github.com/hashicorp/go-version"]
    version = "v1.6.0"
    hash = "sha256-UV0equpmW6BiJnp4W3TZlSJ+PTHuTA+CdOs2JTeHhjs="
  [mod."github.com/hashicorp/hc-install"]
    version = "v0.4.0"
    hash = "sha256-Rp66cSHsaBV0ZKCZGg2QuImFIwt4bux5X3TwAlP672k="
  [mod."github.com/hashicorp/terraform-exec"]
    version = "v0.17.2"
    hash = "sha256-KBm6bF+a9fm9bANzJkSuw6cku2Zlf0W78EOwdIp8+YE="
  [mod."github.com/hashicorp/terraform-json"]
    version = "v0.14.0"
    hash = "sha256-wE6092ugvPMGg/XY4E6LdFDjhKI6AnZtU4CouwRhWVc="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/russross/blackfriday/v2"]
    version = "v2.1.0"
    hash = "sha256-R+84l1si8az5yDqd5CYcFrTyNZ1eSYlpXKq6nFt4OTQ="
  [mod."github.com/stretchr/testify"]
    version = "v1.8.0"
    hash = "sha256-LDxBAebK+A06y4vbH7cd1sVBOameIY81Xm8/9OPZh7o="
  [mod."github.com/urfave/cli/v2"]
    version = "v2.11.2"
    hash = "sha256-F47HfLShmd0Blc8co0GVbXEYjSHBiiaRp69We3MaWqs="
  [mod."github.com/xrash/smetrics"]
    version = "v0.0.0-20201216005158-039620a65673"
    hash = "sha256-WGHtW/OkLowkqOYIvXpDOpn9wqdH2+Dyx3+rYwpmvzI="
  [mod."github.com/zclconf/go-cty"]
    version = "v1.10.0"
    hash = "sha256-yjz6JxZKFiT9YxI6rnVpff1epkqbOLNYaigyEkYarfI="
  [mod."golang.org/x/text"]
    version = "v0.3.7"
    hash = "sha256-XH2pUzzQx95O0rak00grQvfACfL+EmZiV7ZzJBkX+XY="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
